version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: 1234567
      MYSQL_DATABASE: nextcloud
    volumes:
      - db-data:/var/lib/mysql
  nextcloud:
    image: nextcloud
    restart: always
    environment: 
      NEXTCLOUD_ADMIN_USER: root
      NEXTCLOUD_ADMIN_PASSWORD: changeme
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: 1234567
      MYSQL_DATABASE: nextcloud
      MYSQL_HOST: db
    ports:
      - 8080:80
    volumes:
      - nextcloud-data:/var/www/html

volumes:
  db-data:
  nextcloud-data:
